### ISSUE TITLE
Helm Charts for eoAPI (Q2)

### ISSUE THREAD

**Issue by kalxas** [EOEPCA/resource-discovery#66]
Initial work on #15 

## Sub-tasks

- [x] https://github.com/developmentseed/eoapi-k8s/issues/95
- [x] https://github.com/developmentseed/eoapi-k8s/issues/97
- [x] https://github.com/developmentseed/eoapi-k8s/issues/132
- [ ] https://github.com/developmentseed/eoapi-k8s/issues/38
