### ISSUE TITLE
Building block design - Contribution Development Seed (Q3)

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/resource-discovery#84]
## Sub-tasks

- [x] Contribute to OGC API Maps design https://github.com/EOEPCA/data-access/issues/123
- [x] Contribute to OGC API Coverages design https://github.com/EOEPCA/data-access/issues/119
- [x] Contribute to software architecture discussions https://github.com/EOEPCA/data-access/issues/108
- [x] Contribute to auth considerations https://github.com/EOEPCA/resource-discovery/issues/101
- [ ] #98
